# Site settings
title: Stand Against Spying
email: webmaster@eff.org
description: ""
baseurl: "../"
url: "https://standagainstspying.org"
destination: "../docs"

# Build settings
markdown: kramdown
permalink: pretty
